CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS harbour_roles
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT unique_title_harbour_roles UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS statuses
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_title_statuses UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS harbour_users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login     VARCHAR(100) NOT NULL,
    password  VARCHAR(100) NOT NULL,
    role_id   INTEGER NOT NULL,
    status_id INTEGER NOT NULL,
    is_online INTEGER DEFAULT 0,
    PRIMARY KEY (id),

    CONSTRAINT fk_user_role
        FOREIGN KEY (role_id)
            REFERENCES harbour_roles (id),
    CONSTRAINT fk_user_status
        FOREIGN KEY (status_id)
            REFERENCES statuses (id),
    CONSTRAINT unique_login_harbour_users UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS reports
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    text         VARCHAR(300) NOT NULL,
    user_from_id INTEGER       NOT NULL,
    user_to_id   INTEGER       NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_report_user_from
        FOREIGN KEY (user_from_id)
            REFERENCES harbour_users (id),
    CONSTRAINT fk_report_user_to
        FOREIGN KEY (user_to_id)
            REFERENCES harbour_users (id)
);

CREATE TABLE IF NOT EXISTS piers
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS products
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title          VARCHAR(100) NOT NULL,
    quantity       INTEGER NOT NULL,
    captain_id     INTEGER NOT NULL,
    pier_id        INTEGER,
    arrival_date   DATE   NOT NULL,
    departure_date DATE,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_pier
        FOREIGN KEY (pier_id)
            REFERENCES piers (id),
    CONSTRAINT fk_product_user
        FOREIGN KEY (captain_id)
            REFERENCES harbour_users(id)
);


CREATE TABLE IF NOT EXISTS request_statuses
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pier_assignments
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pier_id           INTEGER,
    user_id           INTEGER NOT NULL,
    request_status_id INTEGER NOT NULL,
    CONSTRAINT fk_pier_assignment_pier
        FOREIGN KEY (pier_id)
            REFERENCES piers (id),
    CONSTRAINT fk_pier_assignment_user
        FOREIGN KEY (user_id)
            REFERENCES harbour_users (id),
    CONSTRAINT fk_pier_assignment_request_status
        FOREIGN KEY (request_status_id)
            REFERENCES request_statuses (id)
);