CREATE TABLE harbour_roles
(
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT unique_title_harbour_roles UNIQUE (title)
);

CREATE TABLE statuses
(
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE harbour_users
(
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    login     VARCHAR2(100) NOT NULL,
    password  VARCHAR2(100) NOT NULL,
    role_id   NUMBER NOT NULL,
    status_id NUMBER NOT NULL,
    PRIMARY KEY (id),

    CONSTRAINT fk_user_role
        FOREIGN KEY (role_id)
            REFERENCES harbour_roles (id),
    CONSTRAINT fk_user_status
        FOREIGN KEY (status_id)
            REFERENCES statuses (id),
    CONSTRAINT unique_login_harbour_users UNIQUE (login)
);

CREATE TABLE reports
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    text         VARCHAR(300) NOT NULL,
    user_from_id NUMBER       NOT NULL,
    user_to_id   NUMBER       NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_report_user_from
        FOREIGN KEY (user_from_id)
            REFERENCES harbour_users (id),
    CONSTRAINT fk_report_user_to
        FOREIGN KEY (user_to_id)
            REFERENCES harbour_users (id)
);

CREATE TABLE piers
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE products
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title          VARCHAR2(100) NOT NULL,
    quantity       NUMBER NOT NULL,
    captain_id     NUMBER NOT NULL,
    pier_id        NUMBER,
    arrival_date   DATE   NOT NULL,
    departure_date DATE,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_pier
        FOREIGN KEY (pier_id)
            REFERENCES piers (id),
    CONSTRAINT fk_product_user
        FOREIGN KEY (captain_id)
            REFERENCES harbour_users(id)
);


CREATE TABLE request_statuses
(
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pier_assignments
(
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pier_id           NUMBER,
    user_id           NUMBER NOT NULL,
    request_status_id NUMBER NOT NULL,
    CONSTRAINT fk_pier_assignment_pier
        FOREIGN KEY (pier_id)
            REFERENCES piers (id),
    CONSTRAINT fk_pier_assignment_user
        FOREIGN KEY (user_id)
            REFERENCES harbour_users (id),
    CONSTRAINT fk_pier_assignment_request_status
        FOREIGN KEY (request_status_id)
            REFERENCES request_statuses (id)
);