CREATE TABLE harbour_roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE harbour_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR2(100) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_user_role
        FOREIGN KEY(role_id)
        REFERENCES harbour_roles(id)
);

CREATE TABLE pilots (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(200) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE piers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY(id)
);

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    pier_id NUMBER,
    PRIMARY KEY(id),
    CONSTRAINT fk_product_pier
        FOREIGN KEY(pier_id)
        REFERENCES piers(id)
);

CREATE TABLE pier_assignments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pier_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_pier_assignment_pier
        FOREIGN KEY(pier_id)
        REFERENCES piers(id),
    CONSTRAINT fk_pier_assignment_user
        FOREIGN KEY(user_id)
        REFERENCES harbour_users(id)
);

CREATE TABLE pilot_assignments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pilot_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_pilot_assignment_pilot
        FOREIGN KEY(pilot_id)
        REFERENCES pilots(id),
    CONSTRAINT fk_pilot_assignment_user
        FOREIGN KEY(user_id)
        REFERENCES harbour_users(id)
);