ALTER TABLE products DROP CONSTRAINT fk_product_pier;
ALTER TABLE harbour_users DROP CONSTRAINT fk_user_role;
ALTER TABLE harbour_users DROP CONSTRAINT fk_user_status;
ALTER TABLE pier_assignments DROP CONSTRAINT fk_pier_assignment_pier;
ALTER TABLE pier_assignments DROP CONSTRAINT fk_pier_assignment_user;
ALTER TABLE pier_assignments DROP CONSTRAINT fk_pier_assignment_request_status;
ALTER TABLE reports DROP CONSTRAINT fk_report_user_from;
ALTER TABLE reports DROP CONSTRAINT fk_report_user_to;
DROP TABLE products;
DROP TABLE piers;
DROP TABLE harbour_roles;
DROP TABLE harbour_users;
DROP TABLE pier_assignments;
DROP TABLE reports;
DROP TABLE statuses;
DROP TABLE request_statuses;